### ISSUE TITLE
Bootloader

### ISSUE THREAD

**Issue by diegozalez** [westrup/weather#1]
Hellow, first I want to congratulate you for the amazing work you did, I’m trying to build a bord from scratch and I’m havibg problems to understand the steps of loading a bootloader on to an nRF52, from soldering the chip to being able to have arduino code in it, if you could tell me where can I find more on this that will be a great help.

**Comment by westrup** [comment]
Hi,
This question is not related to this code repository, and I have never used Arduino on nRF52 so I don't think I can help you that much. I found this page that could give you some info: https://github.com/sandeepmistry/arduino-nRF5
